version: '2'
services:

  web:
    image: nginx:latest
    ports:
        - "80:80"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./infra/fluentd
    volumes:
      - ./infra/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
